DROP TABLE xHANAGENERAL;
DROP TABLE xHANA_SID_HOST;
DROP TABLE xHANA_HOST_PARA;
DROP TABLE xHANA_SOLUTION_SID;
DROP TABLE xHANAHOST;
DROP TABLE xHANASOLUTION;
DROP TABLE xHANADATACENTER;
DROP TABLE xHANA_SID_PARA;
DROP TABLE xHANAPARAMETER;
DROP TABLE xHANASID;
DROP TABLE xHANAARC;

